name: neptune_parser
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Modestas Valauskas <valauskasmodestas@gmail.com>

environment:
  sdk: '>=2.4.4'

dependencies:
  test: 1.9.3
  meta: any
  neptune_lexer:
    path: ../neptune_lexer

dev_dependencies:
  extra_pedantic: 1.1.1