name: neptune_language_framework
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.4.4'

dependencies:
  test: 1.9.3
  meta: any
  neptune_lexer:
    path: ../neptune_lexer
  neptune_parser:
    path: ../neptune_parser

dev_dependencies:
  extra_pedantic: 1.1.1
